// Database types will be generated by: npx supabase gen types typescript --local
// For now, define the app-level role enum used across the app

export type UserRole = "admin" | "agent" | "customer_manager";

export type TicketStatus = "open" | "in_progress" | "waiting" | "resolved" | "closed";

export type TicketPriority = "low" | "medium" | "high" | "urgent";

export type SenderType = "customer" | "agent" | "system";
